default:
  retry:
    max: 2 # two retries maximum, three runs in total
    when:
      - runner_system_failure

# Remove duplicate work for branches with open merge requests
# Based on https://docs.gitlab.com/ee/ci/yaml/workflow.html#switch-between-branch-pipelines-and-merge-request-pipelines
workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - if: '$CI_COMMIT_BRANCH'


build-debug:
  image: ghcr.io/lingo-db/lingodb-dev:999de4e4508110da7d4729daaaf3a32371f40059  
  script:
    - make clean
    - make build-debug
    - tar -cvzf lingodb_debug.tar.gz build/lingodb-debug/mlir-db-opt build/lingodb-debug/run-sql build/lingodb-debug/run-mlir build/lingodb-debug/sql build/lingodb-debug/sqlite-tester build/lingodb-debug/test/ build/lingodb-debug/sql-to-mlir
  tags:
    - "umbra-builder"
  artifacts:
    paths:
      - lingodb_debug.tar.gz
    expire_in: 1 hrs

build-release:
  image: ghcr.io/lingo-db/lingodb-dev:999de4e4508110da7d4729daaaf3a32371f40059  
  script:
    - make clean
    - make build-release
    - tar -cvzf lingodb_release.tar.gz build/lingodb-release/mlir-db-opt build/lingodb-release/run-sql build/lingodb-release/run-mlir build/lingodb-release/sql build/lingodb-release/sqlite-tester build/lingodb-release/test/ build/lingodb-release/sql-to-mlir
  tags:
    - "umbra-builder"
  artifacts:
    paths:
      - lingodb_release.tar.gz
    expire_in: 1 hrs

lint:
  image: ghcr.io/lingo-db/lingodb-dev:999de4e4508110da7d4729daaaf3a32371f40059  
  script:
    - make clean
    - make lint
  tags:
    - "umbra-builder"

test:
  image: ghcr.io/lingo-db/lingodb-dev:999de4e4508110da7d4729daaaf3a32371f40059  
  needs:
    - build-debug
  script:
    - make clean
    - tar -xvzf lingodb_debug.tar.gz
    - touch build/dependencies
    - touch build/lingodb-debug/.stamp
    - touch build/lingodb-debug/.buildstamp
    - make test-no-rebuild
  tags:
    - "umbra-integration"

sqlite-tests:
  image: ghcr.io/lingo-db/lingodb-dev:999de4e4508110da7d4729daaaf3a32371f40059  
  needs:
    - build-release
  script:
    - make clean
    - tar -xvzf lingodb_release.tar.gz
    - touch build/dependencies
    - touch build/lingodb-release/.stamp
    - touch build/lingodb-release/.buildstamp
    - make sqlite-test-no-rebuild
  tags:
    - "umbra-integration"

sqlite-dataset-tests:
  image: ghcr.io/lingo-db/lingodb-dev:999de4e4508110da7d4729daaaf3a32371f40059  
  needs:
    - build-release
  script:
    - export BASE_PATH=$(pwd)
    - make clean
    - tar -xvzf lingodb_release.tar.gz
    - touch build/dependencies
    - touch build/lingodb-release/.stamp
    - touch build/lingodb-release/.buildstamp
    - mkdir -p /datasets/tpch-1
    - mkdir -p /datasets/tpcds-1
    - mkdir -p /data
    - cp -r /opt/data/umbra/tpch1 /data/tpch-1
    - cd /data/tpch-1
    - for table in ./*.tbl; do  sed -i 's/|$//' "$table"; done
    - $BASE_PATH/build/lingodb-release/sql /datasets/tpch-1 < $BASE_PATH/resources/sql/tpch/initialize.sql
    - cp -r /opt/data/umbra/tpcds1 /data/tpds-1
    - cd /data/tpds-1
    - for table in ./*.dat; do  sed -i 's/|$//' "$table"; done
    - $BASE_PATH/build/lingodb-release/sql /datasets/tpcds-1 < $BASE_PATH/resources/sql/tpcds/initialize.sql
    - cd $BASE_PATH
    - build/lingodb-release/sqlite-tester ./test/sqlite-datasets/tpchSf1.test /datasets/tpch-1
    - build/lingodb-release/sqlite-tester ./test/sqlite-datasets/tpcdsSf1.test /datasets/tpcds-1
  tags:
    - "umbra-integration"

build_pylingodb:
  image: ghcr.io/lingo-db/lingodb-py-dev:313ae67dd4c39b7af54aae98b8d97ed1d6a452fc  
  script:
    - rm -rf /built-packages
    - mkdir -p /built-packages
    - bash tools/python/bridge/create_package.sh cp312-cp312
    - cd tools/python
    - /opt/python/cp311-cp311/bin/python3 -m build .
    - cp dist/*.whl /built-packages/.
    - cd ../..
    - cp -r /built-packages built-packages
  tags:
    - "umbra-builder"
  artifacts:
    paths:
      - built-packages/*.whl
    expire_in: 1 hrs

test_pylingodb:
   image: ghcr.io/lingo-db/lingodb-dev:999de4e4508110da7d4729daaaf3a32371f40059  
   needs:
      - build_pylingodb
   script:
      - apt-get update
      - apt install -y python3.12-venv
      - python3.12 -m venv venv
      - . venv/bin/activate
      - pip install built-packages/*.whl
      - pip install pandas
      - python3 tools/python/test/test.py
      - python3 tools/python/test/mlir-construction.py
   tags:
      - "umbra-test"

coverage:
  image: ghcr.io/lingo-db/lingodb-dev:999de4e4508110da7d4729daaaf3a32371f40059  
  script:
    - make coverage
  coverage: '/coverage: \d+.?\d*\%/'
  artifacts:
    paths:
      - build/coverage-report
    expire_in: 24 hrs
  #rules:
  #  - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  tags:
    - "umbra-builder"