#ifndef LINGODB_COMPILER_DIALECT_SUBOPERATOR_SUBOPERATOROPSATTRIBUTES_H
#define LINGODB_COMPILER_DIALECT_SUBOPERATOR_SUBOPERATOROPSATTRIBUTES_H

#include "mlir/IR/Dialect.h"
#include "mlir/IR/OpDefinition.h"
#define GET_ATTRDEF_CLASSES
#include "lingodb/compiler/Dialect/SubOperator/SubOperatorOpsAttributes.h.inc"

#endif //LINGODB_COMPILER_DIALECT_SUBOPERATOR_SUBOPERATOROPSATTRIBUTES_H