#ifndef LINGODB_COMPILER_DIALECT_TUPLESTREAM_TUPLESTREAMOPSTYPES_H
#define LINGODB_COMPILER_DIALECT_TUPLESTREAM_TUPLESTREAMOPSTYPES_H

#include "mlir/IR/Dialect.h"
#include "mlir/IR/OpDefinition.h"

#define GET_TYPEDEF_CLASSES
#include "lingodb/compiler/Dialect/TupleStream/TupleStreamOpsTypes.h.inc"

#endif //LINGODB_COMPILER_DIALECT_TUPLESTREAM_TUPLESTREAMOPSTYPES_H
