//RUN: run-mlir %s %S/../../../resources/data/test| FileCheck %s
//CHECK: |                           str  |                       float32  |                       float64  |                       decimal  |                         int32  |                         int64  |                          bool  |                        date32  |                        date64  |
//CHECK: ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
//CHECK: |                         "str"  |                           1.1  |                           1.1  |                          1.10  |                             1  |                             1  |                          true  |                    1996-01-02  |                    1996-01-02  |
//CHECK: |                          null  |                          null  |                          null  |                          null  |                          null  |                          null  |                          null  |                          null  |                          null  |
module {
  func.func @main() {
    %0 = subop.get_external "{ \22table\22: \22test\22, \22mapping\22: { \22booln0\22 :\22bool\22,\22date32n0\22 :\22date32\22,\22date64n0\22 :\22date64\22,\22decimaln0\22 :\22decimal\22,\22float32n0\22 :\22float32\22,\22float64n0\22 :\22float64\22,\22int32n0\22 :\22int32\22,\22int64n0\22 :\22int64\22,\22strn0\22 :\22str\22} }" : !subop.table<[booln0 : !db.nullable<i1>, date32n0 : !db.nullable<!db.date<day>>, date64n0 : !db.nullable<!db.date<millisecond>>, decimaln0 : !db.nullable<!db.decimal<5, 2>>, float32n0 : !db.nullable<f32>, float64n0 : !db.nullable<f64>, int32n0 : !db.nullable<i32>, int64n0 : !db.nullable<i64>, strn0 : !db.nullable<!db.string>]>
    %1 = subop.scan %0 : !subop.table<[booln0 : !db.nullable<i1>, date32n0 : !db.nullable<!db.date<day>>, date64n0 : !db.nullable<!db.date<millisecond>>, decimaln0 : !db.nullable<!db.decimal<5, 2>>, float32n0 : !db.nullable<f32>, float64n0 : !db.nullable<f64>, int32n0 : !db.nullable<i32>, int64n0 : !db.nullable<i64>, strn0 : !db.nullable<!db.string>]> {booln0 => @test::@bool({type = !db.nullable<i1>}), date32n0 => @test::@date32({type = !db.nullable<!db.date<day>>}), date64n0 => @test::@date64({type = !db.nullable<!db.date<millisecond>>}), decimaln0 => @test::@decimal({type = !db.nullable<!db.decimal<5, 2>>}), float32n0 => @test::@float32({type = !db.nullable<f32>}), float64n0 => @test::@float64({type = !db.nullable<f64>}), int32n0 => @test::@int32({type = !db.nullable<i32>}), int64n0 => @test::@int64({type = !db.nullable<i64>}), strn0 => @test::@str({type = !db.nullable<!db.string>})}
    %2 = subop.create !subop.result_table<[strp0 : !db.nullable<!db.string>, float32p0 : !db.nullable<f32>, float64p0 : !db.nullable<f64>, decimalp0 : !db.nullable<!db.decimal<5, 2>>, int32p0 : !db.nullable<i32>, int64p0 : !db.nullable<i64>, boolp0 : !db.nullable<i1>, date32p0 : !db.nullable<!db.date<day>>, date64p0 : !db.nullable<!db.date<millisecond>>]>
    subop.materialize %1 {@test::@bool => boolp0, @test::@date32 => date32p0, @test::@date64 => date64p0, @test::@decimal => decimalp0, @test::@float32 => float32p0, @test::@float64 => float64p0, @test::@int32 => int32p0, @test::@int64 => int64p0, @test::@str => strp0}, %2 : !subop.result_table<[strp0 : !db.nullable<!db.string>, float32p0 : !db.nullable<f32>, float64p0 : !db.nullable<f64>, decimalp0 : !db.nullable<!db.decimal<5, 2>>, int32p0 : !db.nullable<i32>, int64p0 : !db.nullable<i64>, boolp0 : !db.nullable<i1>, date32p0 : !db.nullable<!db.date<day>>, date64p0 : !db.nullable<!db.date<millisecond>>]>
    %res = subop.create_from ["str", "float32", "float64", "decimal", "int32", "int64", "bool", "date32", "date64"] %2 : !subop.result_table<[strp0 : !db.nullable<!db.string>, float32p0 : !db.nullable<f32>, float64p0 : !db.nullable<f64>, decimalp0 : !db.nullable<!db.decimal<5, 2>>, int32p0 : !db.nullable<i32>, int64p0 : !db.nullable<i64>, boolp0 : !db.nullable<i1>, date32p0 : !db.nullable<!db.date<day>>, date64p0 : !db.nullable<!db.date<millisecond>>]> -> !subop.local_table<[strp0 : !db.nullable<!db.string>, float32p0 : !db.nullable<f32>, float64p0 : !db.nullable<f64>, decimalp0 : !db.nullable<!db.decimal<5, 2>>, int32p0 : !db.nullable<i32>, int64p0 : !db.nullable<i64>, boolp0 : !db.nullable<i1>, date32p0 : !db.nullable<!db.date<day>>, date64p0 : !db.nullable<!db.date<millisecond>>]>
    subop.set_result 0 %res : !subop.local_table<[strp0 : !db.nullable<!db.string>, float32p0 : !db.nullable<f32>, float64p0 : !db.nullable<f64>, decimalp0 : !db.nullable<!db.decimal<5, 2>>, int32p0 : !db.nullable<i32>, int64p0 : !db.nullable<i64>, boolp0 : !db.nullable<i1>, date32p0 : !db.nullable<!db.date<day>>, date64p0 : !db.nullable<!db.date<millisecond>>]>
    return
  }
}