//RUN: env LINGODB_EXECUTION_MODE=DEFAULT run-mlir %s %S/../../../resources/data/test| FileCheck %s
//RUN: %if baseline-backend %{LINGODB_EXECUTION_MODE=BASELINE run-mlir %s %S/../../../resources/data/test | FileCheck %s %}

//CHECK: |                           str  |                       float32  |                       float64  |                       decimal  |                         int32  |                         int64  |                          bool  |                        date32  |                        date64  |                         char1  |                        char20  |
//CHECK: ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
//CHECK: |                         "str"  |                           1.1  |                           1.1  |                          1.10  |                             1  |                             1  |                          true  |                    1996-01-02  | 1996-01-02 13:37:00.000000000  |                             a  |        "abcdefghijklmnopqrst"  |
//CHECK: |                          null  |                          null  |                          null  |                          null  |                          null  |                          null  |                          null  |                          null  |                          null  |                          null  |                          null  |
module {
  func.func @main() {
    %0 = subop.execution_group (){
      %1 = subop.get_external "{ \22table\22: \22test\22, \22mapping\22: { \22bool$1\22 :\22bool\22,\22char1$1\22 :\22char1\22,\22char20$1\22 :\22char20\22,\22date32$1\22 :\22date32\22,\22date64$1\22 :\22date64\22,\22decimal$1\22 :\22decimal\22,\22float32$1\22 :\22float32\22,\22float64$1\22 :\22float64\22,\22int32$1\22 :\22int32\22,\22int64$1\22 :\22int64\22,\22str$1\22 :\22str\22} }" : !subop.table<[bool$1 : !db.nullable<i1>, char1$1 : !db.nullable<!db.char<1>>, char20$1 : !db.nullable<!db.char<20>>, date32$1 : !db.nullable<!db.date<day>>, date64$1 : !db.nullable<!db.timestamp<nanosecond>>, decimal$1 : !db.nullable<!db.decimal<5, 2>>, float32$1 : !db.nullable<f32>, float64$1 : !db.nullable<f64>, int32$1 : !db.nullable<i32>, int64$1 : !db.nullable<i64>, str$1 : !db.nullable<!db.string>], false>
      %2 = subop.scan %1 : !subop.table<[bool$1 : !db.nullable<i1>, char1$1 : !db.nullable<!db.char<1>>, char20$1 : !db.nullable<!db.char<20>>, date32$1 : !db.nullable<!db.date<day>>, date64$1 : !db.nullable<!db.timestamp<nanosecond>>, decimal$1 : !db.nullable<!db.decimal<5, 2>>, float32$1 : !db.nullable<f32>, float64$1 : !db.nullable<f64>, int32$1 : !db.nullable<i32>, int64$1 : !db.nullable<i64>, str$1 : !db.nullable<!db.string>], false> {bool$1 => @test::@bool({type = !db.nullable<i1>}), char1$1 => @test::@char1({type = !db.nullable<!db.char<1>>}), char20$1 => @test::@char20({type = !db.nullable<!db.char<20>>}), date32$1 => @test::@date32({type = !db.nullable<!db.date<day>>}), date64$1 => @test::@date64({type = !db.nullable<!db.timestamp<nanosecond>>}), decimal$1 => @test::@decimal({type = !db.nullable<!db.decimal<5, 2>>}), float32$1 => @test::@float32({type = !db.nullable<f32>}), float64$1 => @test::@float64({type = !db.nullable<f64>}), int32$1 => @test::@int32({type = !db.nullable<i32>}), int64$1 => @test::@int64({type = !db.nullable<i64>}), str$1 => @test::@str({type = !db.nullable<!db.string>})}
      %3 = subop.create !subop.result_table<[str$0 : !db.nullable<!db.string>, float32$0 : !db.nullable<f32>, float64$0 : !db.nullable<f64>, decimal$0 : !db.nullable<!db.decimal<5, 2>>, int32$0 : !db.nullable<i32>, int64$0 : !db.nullable<i64>, bool$0 : !db.nullable<i1>, date32$0 : !db.nullable<!db.date<day>>, date64$0 : !db.nullable<!db.timestamp<nanosecond>>, char1$0 : !db.nullable<!db.char<1>>, char20$0 : !db.nullable<!db.char<20>>]>
      subop.materialize %2 {@test::@bool => bool$0, @test::@char1 => char1$0, @test::@char20 => char20$0, @test::@date32 => date32$0, @test::@date64 => date64$0, @test::@decimal => decimal$0, @test::@float32 => float32$0, @test::@float64 => float64$0, @test::@int32 => int32$0, @test::@int64 => int64$0, @test::@str => str$0}, %3 : !subop.result_table<[str$0 : !db.nullable<!db.string>, float32$0 : !db.nullable<f32>, float64$0 : !db.nullable<f64>, decimal$0 : !db.nullable<!db.decimal<5, 2>>, int32$0 : !db.nullable<i32>, int64$0 : !db.nullable<i64>, bool$0 : !db.nullable<i1>, date32$0 : !db.nullable<!db.date<day>>, date64$0 : !db.nullable<!db.timestamp<nanosecond>>, char1$0 : !db.nullable<!db.char<1>>, char20$0 : !db.nullable<!db.char<20>>]>
      %4 = subop.create_from ["str", "float32", "float64", "decimal", "int32", "int64", "bool", "date32", "date64", "char1", "char20"] %3 : !subop.result_table<[str$0 : !db.nullable<!db.string>, float32$0 : !db.nullable<f32>, float64$0 : !db.nullable<f64>, decimal$0 : !db.nullable<!db.decimal<5, 2>>, int32$0 : !db.nullable<i32>, int64$0 : !db.nullable<i64>, bool$0 : !db.nullable<i1>, date32$0 : !db.nullable<!db.date<day>>, date64$0 : !db.nullable<!db.timestamp<nanosecond>>, char1$0 : !db.nullable<!db.char<1>>, char20$0 : !db.nullable<!db.char<20>>]> -> !subop.local_table<[str$0 : !db.nullable<!db.string>, float32$0 : !db.nullable<f32>, float64$0 : !db.nullable<f64>, decimal$0 : !db.nullable<!db.decimal<5, 2>>, int32$0 : !db.nullable<i32>, int64$0 : !db.nullable<i64>, bool$0 : !db.nullable<i1>, date32$0 : !db.nullable<!db.date<day>>, date64$0 : !db.nullable<!db.timestamp<nanosecond>>, char1$0 : !db.nullable<!db.char<1>>, char20$0 : !db.nullable<!db.char<20>>], ["str", "float32", "float64", "decimal", "int32", "int64", "bool", "date32", "date64", "char1", "char20"]>
      subop.execution_group_return %4 : !subop.local_table<[str$0 : !db.nullable<!db.string>, float32$0 : !db.nullable<f32>, float64$0 : !db.nullable<f64>, decimal$0 : !db.nullable<!db.decimal<5, 2>>, int32$0 : !db.nullable<i32>, int64$0 : !db.nullable<i64>, bool$0 : !db.nullable<i1>, date32$0 : !db.nullable<!db.date<day>>, date64$0 : !db.nullable<!db.timestamp<nanosecond>>, char1$0 : !db.nullable<!db.char<1>>, char20$0 : !db.nullable<!db.char<20>>], ["str", "float32", "float64", "decimal", "int32", "int64", "bool", "date32", "date64", "char1", "char20"]>
    } -> !subop.local_table<[str$0 : !db.nullable<!db.string>, float32$0 : !db.nullable<f32>, float64$0 : !db.nullable<f64>, decimal$0 : !db.nullable<!db.decimal<5, 2>>, int32$0 : !db.nullable<i32>, int64$0 : !db.nullable<i64>, bool$0 : !db.nullable<i1>, date32$0 : !db.nullable<!db.date<day>>, date64$0 : !db.nullable<!db.timestamp<nanosecond>>, char1$0 : !db.nullable<!db.char<1>>, char20$0 : !db.nullable<!db.char<20>>], ["str", "float32", "float64", "decimal", "int32", "int64", "bool", "date32", "date64", "char1", "char20"]>
    subop.set_result 0 %0 : !subop.local_table<[str$0 : !db.nullable<!db.string>, float32$0 : !db.nullable<f32>, float64$0 : !db.nullable<f64>, decimal$0 : !db.nullable<!db.decimal<5, 2>>, int32$0 : !db.nullable<i32>, int64$0 : !db.nullable<i64>, bool$0 : !db.nullable<i1>, date32$0 : !db.nullable<!db.date<day>>, date64$0 : !db.nullable<!db.timestamp<nanosecond>>, char1$0 : !db.nullable<!db.char<1>>, char20$0 : !db.nullable<!db.char<20>>], ["str", "float32", "float64", "decimal", "int32", "int64", "bool", "date32", "date64", "char1", "char20"]>
    return
  }
}
