name: Clang Tidy Check
on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    container: ghcr.io/lingo-db/lingodb-dev:43a0f11f34e945c0a2217046ba1cf978126dd2e2
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build
        run: |
          export ENABLE_BASELINE_BACKEND=ON
          make clean
          make lint
