name: Clang Tidy Check
on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    container: ghcr.io/lingo-db/lingodb-dev:ba723e305302f60aefe75084c3b0c60e12dbad70
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build
        run: |
          export ENABLE_BASELINE_BACKEND=ON
          make clean
          make lint
