name: Clang Tidy Check
on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    container: ghcr.io/lingo-db/lingodb-dev:00724db81da57873a65818cc8dfe7e3e2a1090b3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build
        run: |
          export ENABLE_BASELINE_BACKEND=ON
          make clean
          make lint
