name: Clang Format Check

on: [ pull_request ]

jobs:
  clang-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install clang-format
        run: |
          echo "deb http://apt.llvm.org/noble/ llvm-toolchain-noble-20 main" | sudo tee /etc/apt/sources.list.d/llvm-toolchain-noble-20.list > /dev/null && \
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add - && \
          sudo apt update && \
          sudo apt-get install -y clang-format-20

      - name: Run clang-format
        run: make format
      - name: Check for unformatted files
        run: |
          if ! git diff --quiet; then
            echo "Code is not properly formatted. Run clang-format to fix formatting."
            git --no-pager diff
            exit 1
          fi
